# Generated by Django 4.2.13 on 2026-04-04 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('target_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentual da renda mensal destinado a este grupo', max_digits=5, verbose_name='% Alvo do Orçamento')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Cor (hex)')),
                ('icon', models.CharField(default='layers', max_length=50, verbose_name='Ícone (Lucide)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Despesa',
                'verbose_name_plural': 'Grupos de Despesa',
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Item')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item de Despesa',
                'verbose_name_plural': 'Itens de Despesa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('debit', 'Débito'), ('credit', 'Crédito'), ('pix', 'Pix'), ('transfer', 'Transferência'), ('other', 'Outro')], default='pix', max_length=10, verbose_name='Forma de Pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='É recorrente?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.expenseitem', verbose_name='Item de Despesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income_target', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Renda Mensal Esperada')),
                ('currency_symbol', models.CharField(default='R$', max_length=5, verbose_name='Símbolo da Moeda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='InvestmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('investment_type', models.CharField(choices=[('fixed', 'Renda Fixa'), ('variable', 'Renda Variável'), ('reserve', 'Reserva de Emergência')], max_length=10, verbose_name='Tipo')),
                ('icon', models.CharField(default='trending-up', max_length=50, verbose_name='Ícone (Lucide)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Investimento',
                'verbose_name_plural': 'Categorias de Investimento',
                'ordering': ['investment_type', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Aplicado')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o valor aplicado', max_digits=12, null=True, verbose_name='Valor Atual')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='core.investmentcategory', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(default='circle-dollar-sign', max_length=50, verbose_name='Ícone (Lucide)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Receita',
                'verbose_name_plural': 'Categorias de Receita',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('recurrence', models.CharField(choices=[('none', 'Sem recorrência'), ('monthly', 'Mensal'), ('annual', 'Anual')], default='none', max_length=10, verbose_name='Recorrência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='core.incomecategory', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Meta')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('term', models.CharField(choices=[('short', 'Curto Prazo (até 1 ano)'), ('medium', 'Médio Prazo (1 a 5 anos)'), ('long', 'Longo Prazo (acima de 5 anos)')], max_length=10, verbose_name='Prazo')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Acumulado')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Data Alvo')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('achieved', 'Conquistada'), ('paused', 'Pausada')], default='active', max_length=10, verbose_name='Status')),
                ('icon', models.CharField(default='target', max_length=50, verbose_name='Ícone (Lucide)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ['term', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Subgrupo')),
                ('icon', models.CharField(default='tag', max_length=50, verbose_name='Ícone (Lucide)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='core.expensegroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Subgrupo de Despesa',
                'verbose_name_plural': 'Subgrupos de Despesa',
                'ordering': ['order', 'name'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.expensesubgroup', verbose_name='Subgrupo'),
        ),
        migrations.CreateModel(
            name='EmergencyReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta da Reserva')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atual')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reserve', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de Emergência',
                'verbose_name_plural': 'Reservas de Emergência',
            },
        ),
        migrations.AlterUniqueTogether(
            name='expenseitem',
            unique_together={('subgroup', 'name')},
        ),
    ]
