# Generated by Django 4.2.13 on 2026-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_projected',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente pelo sistema para despesas recorrentes projetadas', verbose_name='É projeção automática?'),
        ),
    ]
